#!/bin/zsh

# Sync local site folders to remote servers with rsync (SSH).
# Copyright © 2025-2026 Gustaf Mossakowski
# SPDX-License-Identifier: MIT

#r = recurse into directories
#L = transform symlink into referent file/dir
#p = preserve permissions
#t = preserve times
#D = preserve device files (super-user only), special files
#u = skip files that are newer on the receiver
#v =  increase verbosity

folder="$HOME/Sites"
if [[ ! -d "$folder/$1" ]]; then
	echo "No site $1 available"
	exit
fi
if [[ ! -f "$folder/$1/.rsync-filter" ]]; then
	echo "Missing .rsync-filter for $1"
	exit
fi
if [[ ! -f "$folder/$1/.rsync-remote" ]]; then
	echo "Missing .rsync-remote for $1"
	exit
fi
if [[ ! -f "$folder/$1/.rsync-port" ]]; then
	port=22
else
	while read line; do 
		port=$line
	done < "$folder/$1/.rsync-port"
fi

while read line; do    
    remote=$line
done < "$folder/$1/.rsync-remote"

if [[ $2 == "test" ]] then
	echo "-- Test run --"
	rsync -rLtDuvcin -e "ssh -p $port" --no-perms --no-owner --no-group --no-times --filter="merge $folder/$1/.rsync-filter" $folder/$1/ $remote --delete | grep -E '^deleting|[^/]$|^$'
elif [[ $2 == "inittest" ]] then
	echo "-- Test inital run (get data from remote) --"
	rsync -rLtDuvcin -e "ssh -p $port" --no-perms --no-owner --no-group --no-times --filter="merge $folder/$1/.rsync-filter" $remote $folder/$1/ --delete | grep -E '^deleting|[^/]$|^$'
elif [[ $2 == "init" ]] then
	echo "-- Inital run (get data from remote) --"
	rsync -rLtDuvc -e "ssh -p $port" --filter="merge $folder/$1/.rsync-filter" $remote $folder/$1/ --delete | grep -E '^deleting|[^/]$|^$'
elif [[ $2 == "command" ]] then
	echo "rsync -e 'ssh -p $port' -rLtDuvcn --no-perms --no-owner --no-group --no-times --filter=\"merge $folder/$1/.rsync-filter\" $folder/$1/ $remote --delete | grep -E '^deleting|[^/]$|^$'"
elif [[ $2 == "commandinit" ]] then
	echo "rsync -rLtDuvcin -e 'ssh -p $port' --filter=\"merge $folder/$1/.rsync-filter\" $remote $folder/$1/ --delete | grep -E '^deleting|[^/]$|^$'"
elif [[ $2 == "go" ]] then
	echo "-- Site sync --"
	rsync -rLtDuvc -e "ssh -p $port" --no-perms --no-owner --no-group --no-times --filter="merge $folder/$1/.rsync-filter" $folder/$1/ $remote --delete | grep -E '^deleting|[^/]$|^$' 
fi
